module.exports = {
    MISSING_EMAIL: 'MISSING_EMAIL',
    CANNOT_FIND_USER: 'CANNOT_FIND_USER',
    INVALID_PASSWORD: 'INVALID_PASSWORD',
    EMAIL_EXISTED: 'EMAIL_EXISTED',
    INVALID_SIGN_UP_INFO: 'INVALID_SIGN_UP_INFO'
}
